version: "3.3"
services: 
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: argentinux
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gql-auth-db
    ports:
      - 5432:5432
    volumes:
      - ./prisma/schema.sql:/docker-entrypoint-initdb.d/schema.sql
